- name: instalando no debian
  package:
   name: apache2
  when: ansible_os_family == "Debian"

- name: instalando apache no centos
  package:
   name: httpd
  when: ansible_os_family == "RedHat"

- name: dando start no apache do centos
  service:
   name: httpd
   state: started
  when: ansible_os_family == "RedHat"
