---
# tasks file for confbase

- name: playbook de criacao de usuarios
  include: user.yaml

- name: playbook de instalacao de pacotes
  include: install.yaml

- name: playbook de arquivos padroes
  include: files.yaml

# tasks file for web

- name: playbook de instalacao apache
  include: install_web.yaml

- name: playbook de configuração apache
  include: conf.yaml
